run_times: 'single'
place: 'Cambodia_200'
startYear: 1990
endYear: 2021
seedSpacing: 10
randomPts: 50000
image_source: 'servir'
assetsRoot: 'users/clarype/'
assetsChild: 'LTOP_Py2_5000'
aoi: ee.FeatureCollection("users/clarype/cambodia").geometry()    
maxClusters: 5000
minClusters: 5000
param_scoring_inputs: "/vol/v2/LTOP_FTV_Py_outputs/param_scoring2/"
outfile: "/vol/v2/LTOP_FTV_Py_outputs/outfiles2/"
njobs: 8
cloud_bucket: "ltop-py"
testing: "false"
    
# only needed for medoid composites
startDate: '11-20'
endDate: '03-10'
masked: 
  - 'cloud' 
  - 'shadow'
