run_times: 'multiple'
place: 'countries_plus'
startYear: 1990
endYear: 2021
seedSpacing: 10
randomPts: 20000
image_source: 'servir'
assetsRoot: 'projects/ee-ltop-py/assets/'
assetsChild: 'LTOP_py_countries_plus'
aoi: 'None'    
maxClusters: 200
minClusters: 200
param_scoring_inputs: "/vol/v1/proj/LTOP_FTV_Py/"
outfile: "/vol/v1/proj/LTOP_FTV_Py/selected_lt_params/"
njobs: 8
cloud_bucket: "ltop_assets_storage"
    
# only needed for medoid composites
startDate: '11-20'
endDate: '03-10'
masked: 
  - 'cloud' 
  - 'shadow'