run_times: 'single'
place: 'Cambodia_200'
startYear: 1990
endYear: 2021
seedSpacing: 10
randomPts: 10000
image_source: 'servir'
assetsRoot: 'users/clarype/'
assetsChild: 'LTOP_Py'
aoi: ee.FeatureCollection("users/clarype/cambodia").geometry()    
maxClusters: 1000
minClusters: 1000
param_scoring_inputs: "/vol/v2/LTOP_FTV_Py_outputs/param_scoring/"
outfile: "/vol/v2/LTOP_FTV_Py_outputs/outfiles/"
njobs: 8
cloud_bucket: "ltop-py"
testing: "false"
    
# only needed for medoid composites
startDate: '11-20'
endDate: '03-10'
masked: 
  - 'cloud' 
  - 'shadow'
