run_times: 'single'
place: 'Cambodia_200'
startYear: 1990
endYear: 2022
seedSpacing: 10
randomPts: 20000
image_source: 'servir'
assetsRoot: 'projects/servir-mekong/'
assetsChild: 'LTOP_LMK'
aoi: 'None'    
maxClusters: 200
minClusters: 200
param_scoring_inputs: "/home/ubuntu/LTOP_FTV_Py/"
outfile: "/home/ubuntu/LTOP_FTV_Py/selected_lt_params_LMK/"
njobs: 8
cloud_bucket: "ltop_bucket"
testing: "false"
    
# only needed for medoid composites
startDate: '11-20'
endDate: '03-10'
masked: 
  - 'cloud' 
  - 'shadow'
